import { AgentRegistry } from "@/agents/AgentRegistry";
import { PromptBuilder } from "@/prompts";
import { getProjectContext } from "@/services";
import { ensureProjectInitialized } from "@/utils/projectInitialization";
import { inventoryExists } from "@/utils/inventory";
import type { Phase } from "@/conversations/types";
import { formatError } from "@/utils/errors";
import { logError, logInfo } from "@/utils/logger";
import chalk from "chalk";

interface DebugSystemPromptOptions {
  agent: string;
}

export async function runDebugSystemPrompt(options: DebugSystemPromptOptions) {
  try {
    const projectPath = process.cwd();

    logInfo(`🔍 Debug: Loading system prompt for agent '${options.agent}'`);

    // Initialize project context if needed
    await ensureProjectInitialized(projectPath);

    // Load agent from registry
    const agentRegistry = new AgentRegistry(projectPath);
    await agentRegistry.loadFromProject();
    const agent = agentRegistry.getAgent(options.agent);

    console.log(chalk.cyan("\n=== Agent Information ==="));
    if (agent) {
      console.log(chalk.white("Name:"), agent.name);
      console.log(chalk.white("Role:"), agent.role);
      console.log(chalk.white("Expertise:"), agent.expertise);
      if (agent.tools && agent.tools.length > 0) {
        console.log(chalk.white("Tools:"), agent.tools.join(", "));
      }
    } else {
      console.log(chalk.yellow(`Note: Agent '${options.agent}' not found in registry`));
    }

    console.log(chalk.cyan("\n=== System Prompt ==="));

    if (agent) {
      let inventoryPrompt: string | undefined;
      if (await inventoryExists(projectPath)) {
        inventoryPrompt =
          "## Project Inventory\n\nAn inventory file exists for this project. To get detailed project structure and file information, please refer to the inventory file generated by Claude Code.";
      }

      const projectCtx = getProjectContext();
      const project = projectCtx.project;
      const titleTag = project.tags.find((tag) => tag[0] === "title");
      const repoTag = project.tags.find((tag) => tag[0] === "repo");

      const systemPrompt = new PromptBuilder()
        .add("agent-system-prompt", {
          agent,
          phase: "chat" as Phase,
          projectTitle: titleTag?.[1] || "Untitled Project",
          projectRepository: repoTag?.[1] || "No repository",
          inventoryPrompt,
        })
        .build();

      console.log(systemPrompt);
    } else {
      console.log(chalk.yellow(`Agent '${options.agent}' not found in registry`));
    }

    console.log(chalk.cyan("===================\n"));

    logInfo("System prompt displayed successfully");
  } catch (err) {
    const errorMessage = formatError(err);
    logError(`Failed to generate system prompt: ${errorMessage}`);
    process.exit(1);
  }
}
