import { fragmentRegistry } from "../core/FragmentRegistry";
import type { PromptFragment } from "../core/types";

interface ProjectFragmentArgs {
  project: {
    name: string;
    description?: string;
    tags?: string[];
    metadata?: Record<string, unknown>;
  };
  detailed?: boolean;
}

const validateProjectArgs = (args: unknown): args is ProjectFragmentArgs => {
  if (!args || typeof args !== "object" || !("project" in args)) {
    return false;
  }
  const obj = args as Record<string, unknown>;
  return Boolean(
    obj.project &&
      typeof obj.project === "object" &&
      obj.project !== null &&
      "name" in obj.project &&
      typeof (obj.project as Record<string, unknown>).name === "string",
  );
};

export const projectFragment: PromptFragment<ProjectFragmentArgs> = {
  id: "project-context",
  priority: 20,
  template: ({ project, detailed = false }) => {
    let prompt = `---\nProject: ${project.name}`;

    if (detailed && project.description) {
      prompt += `\nDescription: ${project.description}`;
    }

    if (detailed && project.tags && project.tags.length > 0) {
      prompt += `\nTags: ${project.tags.join(", ")}`;
    }

    if (
      detailed &&
      project.metadata &&
      Object.keys(project.metadata).length > 0
    ) {
      prompt += `\nMetadata: ${JSON.stringify(project.metadata, null, 2)}`;
    }

    return prompt;
  },
  validateArgs: validateProjectArgs,
  expectedArgs:
    "{ project: { name: string, description?: string, tags?: string[], metadata?: Record<string, any> }, detailed?: boolean }",
};

// Auto-register
fragmentRegistry.register(projectFragment);

interface InventoryContextArgs {
  hasInventory: boolean;
}

const validateInventoryArgs = (args: unknown): args is InventoryContextArgs => {
  if (!args || typeof args !== "object" || !("hasInventory" in args)) {
    return false;
  }
  const obj = args as Record<string, unknown>;
  return typeof obj.hasInventory === "boolean";
};

export const inventoryContextFragment: PromptFragment<InventoryContextArgs> = {
  id: "project-inventory-context",
  priority: 25,
  template: ({ hasInventory }) => {
    if (!hasInventory) {
      return "";
    }

    return `## Project Inventory

An inventory file exists for this project. To get detailed project structure and file information, please refer to the inventory file generated by Claude Code.`;
  },
  validateArgs: validateInventoryArgs,
  expectedArgs: "{ hasInventory: boolean }",
};

// Auto-register inventory fragment
fragmentRegistry.register(inventoryContextFragment);
